# Generated by Django 4.2.3 on 2023-07-29 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 17, 20, 45, 141229, tzinfo=datetime.timezone.utc)),
        ),
    ]
