# Generated by Django 4.2.3 on 2023-07-29 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 17, 33, 48, 350838, tzinfo=datetime.timezone.utc)),
        ),
    ]
