# Generated by Django 4.2.3 on 2023-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
